---

- set_fact:
    id_rsa: "{{ id_rsa.stdout }}"

- name: install epel repo
  yum:
    name: epel-release
    state: latest
    
- name: install borgbackup
  yum:
    name: borgbackup
    state: latest

- name: Create File System on backup disk
  filesystem:
    fstype: xfs
    dev: /dev/sdb
    force: no

- name: Create borg user
  user:
    name: borg
    createhome: yes
    home: /home/borg

- name: Create /.ssh/ dir
  file:
    path: /home/borg/.ssh/
    state: directory
    owner: borg
    group: borg
    mode: '700'

- name: Create /.ssh/authorized_keys
  file:
    path: /home/borg/.ssh/authorized_keys
    state: touch
    owner: borg
    group: borg
    mode: '600'

- name: Change backupdir ownership /var/backup/
  file:
    path: /var/backup/
    state: directory
    recurse: yes
    owner: borg
    group: borg

- name: mount backup dir
  mount:
    path: /var/backup
    src: /dev/sdb
    fstype: xfs
    opts: defaults
    state: present

- name: add ssh key from client
  shell:  echo 'command="/usr/local/bin/borg serve" {{ rsa }}' > /home/borg/.ssh/authorized_keys
