---

- name: install epel repo
  yum:
    name: epel-release
    state: latest
    
- name: install borgbackup
  yum:
    name: borgbackup
    state: latest

- name: Create borg user
  user:
    name: borg
    create_home: /home/borg

- name: Create /.ssh/ dir
  file:
    path: /home/borg/.ssh/
    owner: borg
    group: borg
    mode: '700'
    
- name: Create /.ssh/authorized_keys
  file:
    path: /home/borg/.ssh/authorized_keys
    owner: borg
    group: borg
    mode: '600'
    
- name: add ssh key from client
  shell:  echo 'command="/usr/local/bin/borg serve" {{ rsa }}' > /home/borg/.ssh/authorized_keys
  
- name: Change backupdir ownership /var/backup/
  file:
    path: /var/backup/
    recurse: yes
    owner: borg
    group: borg
