---

- name: install epel repo
  yum:
    name: epel-release
    state: latest
    
- name: install borgbackup
  yum:
    name: borgbackup
    state: latest

- name: Generate an OpenSSH rsa keypair with a different size (2048 bits)
  community.crypto.openssh_keypair:
    path: /tmp/id_ssh_rsa
    size: 2048

- name: get id rsa
  shell: cat /tmp/id_ssh_rsa.pub
  register: id_rsa

- set_fact: 
    rsa={{ id_rsa.stdout }}

- debug: 
    var: rsa

- name: Create a borg-backup.service
  copy: 
    src: borg-backup.service
    dst: /etc/systemd/system/borg-backup.service
    
- name: Create a borg-backup.timer
  copy:
    src: borg-backup.timer   
    dst: /etc/systemd/system/borg-backup.timer

- name: reload systemctl
  command: systemctl daemon-reload
  
- name: enable borg-backup.service
  command: systemctl enable borg-backup.service

- name: enable borg-backup.timer
  command: systemctl enable borg-backup.timer